### ISSUE TITLE
Certain textures are missing when importing a Source map BSP.

### ISSUE THREAD

**Issue by sog76561198136342500** [REDxEYE/SourceIO#218]
Gives me this error on import:

```
Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\SourceIO\blender_bindings\operators\source1_operators.py", line 133, in execute
    bsp_map.load_materials(self.use_bvlg)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\SourceIO\blender_bindings\source1\bsp\import_bsp.py", line 184, in load_materials
    mat = Source1MaterialLoader(material_file, material_name)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\SourceIO\blender_bindings\material_loader\material_loader.py", line 39, in __init__
    self.vmt: VMT = VMT(file_object, self.material_name)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\SourceIO\library\source1\vmt\__init__.py", line 23, in __init__
    self._postprocess()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\SourceIO\library\source1\vmt\__init__.py", line 37, in _postprocess
    patched_vmt = VMT(original_material, self.get_string('include'))
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\SourceIO\library\source1\vmt\__init__.py", line 21, in __init__
    self.shader, self.data = parser.tree.top()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\SourceIO\library\utils\kv_parser.py", line 63, in top
    key, value = self.data[0]
IndexError: list index out of range
```

I also get this error when trying to load entities/props:

```
Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\SourceIO\blender_bindings\operators\shared_operators.py", line 188, in execute
    import_static_animations(content_manager, model_container.mdl, default_anim,
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\SourceIO\blender_bindings\source1\mdl\v44\import_mdl.py", line 319, in import_static_animations
    bpy.ops.object.mode_set(mode='POSE')
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.mode_set.poll() Context missing active object
```

**Comment by EntityinArray** [comment]
try placing your .bsp file into the maps folder of a game it was designed for and importing from there.

**Comment by REDxEYE** [comment]
Second error should be fixed now

**Comment by MrMage750** [comment]
> try placing your .bsp file into the maps folder of a game it was designed for and importing from there.

mine is and I'm still having a slew of missing textures

I'm starting to get the impression that SourceIO is poorly made, not unlike blendersourcetools. hopefully a third, well made blender addon for importing source assets will release in the near future, because rn I'm gonna be spending hours digging for the missing textures and reassign them to materials, which I have over 250 of these to fix...

**Comment by EntityinArray** [comment]
> > try placing your .bsp file into the maps folder of a game it was designed for and importing from there.
> 
> mine is and I'm still having a slew of missing textures
> 
> I'm starting to get the impression that SourceIO is poorly made, not unlike blendersourcetools. hopefully a third, well made blender addon for importing source assets will release in the near future, because rn I'm gonna be spending hours digging for the missing textures and reassign them to materials, which I have over 250 of these to fix...

you can add me on discord \@cyberplebeian  and we can investigate together

**Comment by REDxEYE** [comment]
> > try placing your .bsp file into the maps folder of a game it was designed for and importing from there.
> 
> mine is and I'm still having a slew of missing textures
> 
> I'm starting to get the impression that SourceIO is poorly made, not unlike blendersourcetools. hopefully a third, well made blender addon for importing source assets will release in the near future, because rn I'm gonna be spending hours digging for the missing textures and reassign them to materials, which I have over 250 of these to fix...

Please note that there are many-many versions of source engine, there may be typos in materials(sourceio has a very strict VMT parser, that does not tolerate errors and just skips lines/files), sourceio requires assets to be in the correct places(random folder on your desktop may work if you placed all the assets in corresponding folders)

Blender Source Tools have much smaller list of requirements. They only import/export 2 formats, sourceio support bsp, mdl, vtf, md3, vwrld, vmdl, vmap including various asset version, there only 6 mdl versions that sourceio support right now +7 or 8 bsp versions, any support for many other version is comming soon. 

Small note, at currently sourceio contains 132584 lines of code, that not easy to maintain this huge codebase

**Comment by MrMage750** [comment]
> > > try placing your .bsp file into the maps folder of a game it was designed for and importing from there.
> > 
> > 
> > mine is and I'm still having a slew of missing textures
> > I'm starting to get the impression that SourceIO is poorly made, not unlike blendersourcetools. hopefully a third, well made blender addon for importing source assets will release in the near future, because rn I'm gonna be spending hours digging for the missing textures and reassign them to materials, which I have over 250 of these to fix...
> 
> Please note that there are many-many versions of source engine, there may be typos in materials(sourceio has a very strict VMT parser, that does not tolerate errors and just skips lines/files), sourceio requires assets to be in the correct places(random folder on your desktop may work if you placed all the assets in corresponding folders)

that's the thing, all assets are in the correct folders.

> Blender Source Tools have much smaller list of requirements. They only import/export 2 formats, sourceio support bsp, mdl, vtf, md3, vwrld, vmdl, vmap including various asset version, there only 6 mdl versions that sourceio support right now +7 or 8 bsp versions, any support for many other version is comming soon.

which is why SourceIO is by far the better of the 2 evils.

> Small note, at currently sourceio contains 132584 lines of code, that not easy to maintain this huge codebase

then hire more devs, it's as simple as that. any projects involving code are not best done alone or in small teams

**Comment by REDxEYE** [comment]
Hire = spend money, SourceIO is not a commercial project, I don't get any money from it. I it was a commercial product you would complain like here https://github.com/rlguy/Blender-FLIP-Fluids/issues/618. If you are sure that everything is in the correct folder then why you didn't provide any logs or info for me? You just complained that you need to manually fix 250 materials

**Comment by MrMage750** [comment]
> Hire = spend money, SourceIO is not a commercial project, I don't get any money from it. I it was a commercial product you would complain like here [rlguy/Blender-FLIP-Fluids#618](https://github.com/rlguy/Blender-FLIP-Fluids/issues/618). If you are sure that everything is in the correct folder then why you didn't provide any logs or info for me? You just complained that you need to manually fix 250 materials

my apologies, I was making some highly fallacious arguments and you snapped me out of my tantrum. I don't see anything worth bringing up in the logs, but it did say to use the latest version of SourceIO for 4.0, which I thought I was using, but I may be wrong. for the map, I was using gm_bigcity, converted into a bsp via gmad, it's a gmod map that's been around for nearly as long as the game existed, and the default maps like gm_construct seem to import just fine, but I can't see why gm_bigcity is different other than the fact that it's an addon

**Comment by MrMage750** [comment]
ok I have legitimately no idea why, but when loading the map in a separate blender session, everything was fine. there must've been something else I did that causes that error, or there may have been a hiccup with blender or the addon, but either way, it would not be any problem on your end. I sincerely apologize for disparaging you and your work, I'll be much more respectful and considerate in the future

**Comment by REDxEYE** [comment]
SourceIO saves mounted content in blend file. Mounted content may interfered.
