### ISSUE TITLE
Static props no longer importing with map file

### ISSUE THREAD

**Issue by Brennan-91** [REDxEYE/SourceIO#225]
I've already imported a couple of maps a couple weeks ago through source.io (all sfm maps from the workshop), and they've all worked fine. But now when I try to import them it doesn't even create a folder for the static props. Is this an issue that needs to be addressed or did I click something wrong and mess it up for myself?

A saved file from an earlier import
![Blender  C__Users_bflan_OneDrive_Documents_Blender Projects_Tutorial_Sp1_revised blend  8_20_2023 9_13_25 PM](https://github.com/REDxEYE/SourceIO/assets/90109821/311a5e15-8bb6-42c9-a520-a711c39545be)

The same map imported just now
![Blender 8_20_2023 9_13_07 PM](https://github.com/REDxEYE/SourceIO/assets/90109821/7506d9cd-d0ed-4e61-9509-5523ddd4ab58)

**Comment by REDxEYE** [comment]
Looks like sourceio crashed during import. Please go to blender system console and look for any errors there

**Comment by MeanBeanMachine2024** [comment]
Couldn't upload it directly so have to use mega https://mega.nz/file/I55ylQQD#_djGlJuUjVYya0lo3QXauDfxhgdBLNu8_SnM88e8V4I

**Comment by REDxEYE** [comment]
SFM/GMod map? Please give me as much info in map as you can

**Comment by MeanBeanMachine2024** [comment]
It's a sfm map, the I believe the models come in the same download as the map but are not in the bsp and are separate. I am using blender 6.6.2 and using the most recent version of this addon that was made yesterday.

**Comment by MeanBeanMachine2024** [comment]
Okay I just imported a map that had all the models in one bsp and that one worked fine

**Comment by MeanBeanMachine2024** [comment]
Awsome!

**Comment by REDxEYE** [comment]
Looks like i fixed the bug

**Comment by MeanBeanMachine2024** [comment]
Nope, downloaded the new version and it's still happening
[Blender Log.txt](https://github.com/REDxEYE/SourceIO/files/12419760/Blender.Log.txt)

**Comment by MeanBeanMachine2024** [comment]
I'm trying to use this map btw https://steamcommunity.com/sharedfiles/filedetails/?id=1496582165&searchtext=splatoon

**Comment by REDxEYE** [comment]
Try again. I think i fixed it

**Comment by MeanBeanMachine2024** [comment]
Yep that worked! Thank you so much!
