### ISSUE TITLE
Importing VTF does not import alpha

### ISSUE THREAD

**Issue by Xiarno** [REDxEYE/SourceIO#62]
I'm not exactly sure it's really confusing.
First both option.
There is "load alpha into separate image" & "only load alpha". Okay, how do I load the image and have the alpha channel use the alpha ? 

In any cases, I tried all 4 combination possible and the alpha just doesn't work. And when using "alpha blend" so the alpha is invisible blablabla you know how it work, well the alpha doesn't work so alpha blend doesn't work.

**Comment by REDxEYE** [comment]
Can you provide an example of such texture?

**Comment by Xiarno** [comment]
Github doesn't support .VTF so I put some in a .ZIP
[BillboardNONCONVERTED.zip](https://github.com/REDxEYE/SourceIO/files/5625704/BillboardNONCONVERTED.zip)

**Comment by REDxEYE** [comment]
https://github.com/REDxEYE/SourceIO/releases/tag/3.8.5.1

Try it with this release

**Comment by Xiarno** [comment]
> https://github.com/REDxEYE/SourceIO/releases/tag/3.8.5.1
> 
> Try it with this release

Working. Thx !
Btw, before you close this. Importing a model and selecting "import material" literally never works. Would be useful if it could import the texture at the same time 'cause when u import 100+ models and have to put like 10 textures on each manually... yeah

**Comment by REDxEYE** [comment]
https://github.com/REDxEYE/SourceIO/releases/tag/3.8.6 Should be fixed in this version

**Comment by Xiarno** [comment]
> https://github.com/REDxEYE/SourceIO/releases/tag/3.8.6 Should be fixed in this version

Doesn't work. Although there is something different happening. Before, if I tried to "import materials", it would put an error (the model still import, but not the texture). Now, if I try to import, there is no error but it still doesn't work.
I don't know if it is related or not, but when going into the material, the "use node" checkbox is not checked.

**Comment by REDxEYE** [comment]
Can you please share the console log?

**Comment by REDxEYE** [comment]
And model you're trying to import

**Comment by Xiarno** [comment]
> Can you please share the console log?

The console log goes out of the windows, I can't scroll high enough

Here's the model(s). GDrive because file is too big https://drive.google.com/file/d/1PwOmI0ME_bmK8oq9BNeaheODeUV_l-Va/view?usp=sharing

**Comment by REDxEYE** [comment]
![image](https://user-images.githubusercontent.com/17544576/100920971-f3138100-34ec-11eb-96d2-fe7ca07658d4.png)
Everything loaded fine for me

**Comment by Xiarno** [comment]
> ![image](https://user-images.githubusercontent.com/17544576/100920971-f3138100-34ec-11eb-96d2-fe7ca07658d4.png)
> Everything loaded fine for me

Huh.... Then idk.
What version of Blender are you using ?

**Comment by REDxEYE** [comment]
2.92

**Comment by Xiarno** [comment]
> 2.92

Oh, I'm using 2.90.1 because 2.91 had a very annoying bug that I reported and will be fixed and can't use 2.92 because it's not on Steam beta.

**Comment by REDxEYE** [comment]
It should work in any version of blender newer than 2.80

**Comment by REDxEYE** [comment]
You can always import multiple materials via .vmt import with enabled override. It will import materials and replace materials on models

**Comment by Xiarno** [comment]
> It should work in any version of blender newer than 2.80

Well I can confirm it doesn't work for 2.90.1, 2.91 and 2.92 for me.



> You can always import multiple materials via .vmt import with enabled override. It will import materials and replace materials on models

I'll try.

**Comment by REDxEYE** [comment]
latest commit should fix this error

**Comment by Xiarno** [comment]
> latest commit should fix this error

Can confirm that importing .vmt is now working. Although importing with material is sadly still not working. But atleast it's a start !

**Comment by REDxEYE** [comment]
Can you give me more details? 
From what folder are you trying to import model?

**Comment by Xiarno** [comment]
> Can you give me more details?
> From what folder are you trying to import model?

I've been using the same files as a example, Aka the zip file I sent you above.

**Comment by REDxEYE** [comment]
Try again

**Comment by Xiarno** [comment]
> Try again

Now I can activate it.
Import material still do not work... 
I'm gonna try on the original SFM folder that I have. -> Nope, still don't.
Also I'm talking about import material when you import models. VMT import are now working, but the "import material" when importing model still do not :/

**Comment by REDxEYE** [comment]
Does D:\SteamLibrary\steamapps\common\SourceFilmmaker\game\Macro contain gameinfo.txt?

**Comment by Xiarno** [comment]
> Does D:\SteamLibrary\steamapps\common\SourceFilmmaker\game\Macro contain gameinfo.txt?

Nope. Only this:
![image](https://user-images.githubusercontent.com/24660485/101373492-ff943280-387a-11eb-902c-b9d830fb3070.png)

Although, I'm not putting my models for SFM in the usermod folder as I've been recommended over & over (And also looking on the forums & all) to not do it to avoid breaking SFM. Thus I'm putting them in their own folder and activating them.
The usermod folder do contain gameinfo.txt:
D:\SteamLibrary\steamapps\common\SourceFilmmaker\game\usermod\gameinfo.txt

**Comment by REDxEYE** [comment]
That's probably why it's failing

**Comment by Xiarno** [comment]
> That's probably why it's failing

Ah, well I'm gonna try to put it in the usermod folder.
I'm not using SFM anymore anyway so I don't really care.
Although if I could suggest a way to avoid this (I do not know coding at all so I'm just saying), maybe make it so it tries to find relative to the file you selected instead of from usermod ? I mean, folder placement for SFM have to be so specific, generally the materials for the model is the same folder setup from the root folder except it's "materials" instead of "models".
Like, if we have a folder called "city", with a model called "citymodel" and a material called "citymaterial", the folder placement (from SFM root folder, aka the "game" folder) would be this:
Model: city\models\afolderhere\citymodel
Material: city\materials\afolderhere\citymaterial

Again, I'm not a coder so I'm just thinking in a logical way but I have no idea if it could work
So if you choosed the model, the addon could like. First, see if it's the usermod folder to do your things, and if it's not, then instead it tries to go from the folder the model was selected in to the folder that contain the "models" folder, look at the materials folder and take the same folder path that was for the models but instead materials and take the corresponding materials.
Again, I have no idea if this could work, I'm just throwing it as an idea.

**Comment by Xiarno** [comment]
As said above, importing material when importing models do not import alpha.

Another problem, more of an annoyance but I think it could be the cause of why it took 1h to import 115 models for the city with materials is that it create the node setup everytime the material exist.
For example, I have all the buildings model and a material is used multiple time. But of course, it's not different material in Blender, it's just used multiple time so no need for different node setup, you jsut have 1 material and use it on differnet model. But the addon will create a node setup evertime a material exist, but only one of them will connect to the material output.
So loads of material are like this: (The one connected to the material output is out of the screenshot, but it's there)
![image](https://user-images.githubusercontent.com/24660485/101385368-b7c8d780-3889-11eb-9c96-7afb58ccff2a.png)
I hope you understand I don't know if I explained it good enough.

**Comment by REDxEYE** [comment]
Ye, it's known issue, i will fix it later

**Comment by Xiarno** [comment]
> Ye, it's known issue, i will fix it later

For the alpha or the creating many node things ?

**Comment by REDxEYE** [comment]
node duplication and proper alpha support were added in latest commits

**Comment by Xiarno** [comment]
> node duplication issue has bee fixed and proper alpha support were added in latest commits

Downloaded the master right now
Still the last problem when activating the addon:

**Comment by REDxEYE** [comment]
You downloaded version while i was changing whole content management system :D

**Comment by Xiarno** [comment]
> You downloaded version while i was changing whole content management system :D

Wow, what an amazing timing
